name: Secret File v2
description: Write a secret to a local file during a workflow
branding:
  icon: lock
  color: purple
inputs:
  secret:
    description: The secret to write to a file
    required: true
  b64-decode:
    description: Indicates whether to base64 decode the secret value
    required: true
  outputs:
    description: secret out
runs:
  using: "node16"
  main: "dist/index.js"

